In [13]:
import mifuncion as mf
mf.mifuncion(1,1,1)

3


AttributeError: module 'mifuncion' has no attribute 'mifuncion2'

In [12]:
import math
g=math.factorial(3)
print(f"este es el factorial:{g} esto es mas ")

este es el factorial:6 esto es mas 


In [59]:
import numpy as np
a = ([1,2,3],[1,2,3],[4,5,6])
b=np.array(a)
a1 =[1,2,3]
a2 = [1,2,3] #estas listas no se pueden sumar se deben comvertir a array
c = a1+a2
# print(b+b)
print(b.shape)#dimension
print(b.sum())
print(b.reshape([1,9]))
print(b.max())
a = np.random.randint(20,size=(3,3))
print(a)

(3, 3)
27
[[1 2 3 1 2 3 4 5 6]]
6
[[ 9  4  9]
 [14  5  1]
 [ 8 12  2]]


In [70]:
import numpy as np
a = ((3,5,7), (2,4,6), (1,2,3))
print(a)
b= np.array(a)
# print(b)
# print(b.mean())
# print(b.max())
# print(b.shape)
# print(b.cumsum())
# print(b.reshape([9,1]))

np.empty((3,2))
a = np.empty((3,2))
print(a)

np.random.randint(10,size=(2))
print (np.random.randint(10,size=(2,8)))


((3, 5, 7), (2, 4, 6), (1, 2, 3))
[[1.16001573 0.01852811]
 [0.02999769 0.84925081]
 [0.61247188 0.74604389]]
[[7 5 5 3 3 8 9 6]
 [8 9 4 7 9 5 3 9]]


In [76]:
import pandas as pd
path = "boston_house_prices.csv"
raw_data = pd.read_csv(path,header = 1)
print(raw_data.columns)
print(raw_data['NOX'])

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')
0      0.538
1      0.469
2      0.469
3      0.458
4      0.458
       ...  
501    0.573
502    0.573
503    0.573
504    0.573
505    0.573
Name: NOX, Length: 506, dtype: float64


In [89]:
import pandas as np
name = "boston_house_prices.csv"
print(name)
data = np.read_csv(name, header=1)
print(data[["NOX","RM"]])


boston_house_prices.csv
       NOX     RM
0    0.538  6.575
1    0.469  6.421
2    0.469  7.185
3    0.458  6.998
4    0.458  7.147
..     ...    ...
501  0.573  6.593
502  0.573  6.120
503  0.573  6.976
504  0.573  6.794
505  0.573  6.030

[506 rows x 2 columns]


In [110]:
from sklearn.datasets import load_boston
print(load_boston().keys())
datos = load_boston()['data']
enca = load_boston()['feature_names']
print(enca)
df =pd.DataFrame(datos,columns= enca)
# df


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [115]:
print(load_boston().keys())
load_boston()["data"]
a = load_boston()["data"]
b = load_boston()["feature_names"]
print(b)
pd.DataFrame(a, columns=[b])

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
