In [3]:
import math
a=math.factorial(10)

x =math.tanh(3)
print(f"factorial:{x}")

factorial:0.9950547536867305


In [12]:
import mifuncion as mf
mf.mifuncion("hola qué hay aquí?")

hola mundo soy una función, llamada desde otro archivo:  hola qué hay aquí?


C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\datasets

In [51]:
import numpy as np
import pandas as pd
a = ([1,2,3],[1,2,3],[4,5,6]) #lista de lista puede tener cualquieir forma
m =np.array(a) # array ya se habla propiamente de vectores y matrices , tiene forma definida
print(m.shape)
# print(m)
print(m.sum())
print(m[1].shape)#sigue siendo un vector
#print(a.shape) #ojo ya es una tupla no se puede ver la forma 
z =m.reshape(1,9)
print(z)

(3, 3)
27
(3,)
[[1 2 3 1 2 3 4 5 6]]


In [189]:
import numpy as np
z= np.zeros((2,4))
a=np.array([1,2,4])
print(a.max())
print(a.min())
print(a.cumsum())
rnd = np.random.randint(5,size=(3,4))
print( rnd)

4
1
[1 3 7]
[[3 3 2 4]
 [3 1 3 4]
 [0 3 4 0]]


In [150]:
import csv
with open("boston_house_prices.csv","r" )as archivo:
    data = csv.reader(archivo)
    print(data)
    # for row in data: 
    #     print(row)

ValueError: I/O operation on closed file.

In [111]:
import numpy as np
# raw_data = open("boston_house_prices.txt")
# data = np.loadtxt(raw_data,delimiter =",")
# print(data)
#ojo si fuera solo de numeros se puede usar numpy


In [157]:
import pandas as pd
path = "boston_house_prices.csv"
data =pd.read_csv(path,header = 1)
print(data.columns)

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')


In [162]:
from sklearn.datasets import load_boston
print(load_boston().keys())
print(load_boston()['feature_names'])

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [192]:
data = load_boston()["data"]
target = load_boston()['feature_names']
baseDatos =pd.DataFrame(data,columns=target)
print(baseDatos.describe())

             CRIM          ZN       INDUS  ...     PTRATIO           B       LSTAT
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...   18.455534  356.674032   12.653063
std      8.601545   23.322453    6.860353  ...    2.164946   91.294864    7.141062
min      0.006320    0.000000    0.460000  ...   12.600000    0.320000    1.730000
25%      0.082045    0.000000    5.190000  ...   17.400000  375.377500    6.950000
50%      0.256510    0.000000    9.690000  ...   19.050000  391.440000   11.360000
75%      3.677083   12.500000   18.100000  ...   20.200000  396.225000   16.955000
max     88.976200  100.000000   27.740000  ...   22.000000  396.900000   37.970000

[8 rows x 13 columns]
